[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
    "-c",
    "tailwindcss -i src/styles/main.css -o target/styles/tailwind_output.css",
]

[[proxy]]
rewrite = "/api/"
backend = "http://0.0.0.0:4242/api"
